# Configuration for monsti-daemon.

# Modules to be started.
# Monsti expects the module binaries to be in $PATH and named
# monsti-<modulename>, e.g. $PATH/monsti-my-addon
# modules: [my-addon, another-addon]
modules: [example-module, taxonomy]

# Listen for HTTP connections on this address and port,
# e.g. localhost:8080, :8080, yourdomain.com:80
#
# You should use a reverse proxy like Nginx and keep Monsti listening
# only on localhost (i.e. the loopback interface).
listen: localhost:8080

# SMTP settings for outgoing mail.
mail:
  # host:port
  host: localhost:25
  #username: user
  #password: password
  # if debug is true, mails will not be send at all but written to the
  # log.
  debug: true
