language: go
go:
- 1.2
env:
  global:
  - secure: gvTA0b2M7wwZRlTmAfMZIxkVLFkqgpUouyGooZJhJ3dFQI7VMLdWQn6U6bHTmkGWaAvoSaSSaDgbxRebP+4hDVqa3yn9S2RSuyXO2E7v8LIm2l+kC7ZK/nd7zb7h4OmP1JlJdOyIY8FjMDCGz7EyJCIZV294u2+RDWdRCLK/pbk=
  - secure: BikjuwDyhE5wKXF77G98YYlQ4+Vz47ckGlpH2UM84pKVirIHTvTCJwTJdKiJS83w+inkGdoRbxk29hkB0B/ShQvZZTIEUlGrhsOJM7TnSfoQGyq7GDuP2zCqgbzOiApNDEqGTTxxiVfasnBo4XpXeBpv62iNV0ixV3C4q4Tnv1Q=
addons:
  sauce_connect: true
script:
  - make test
  - make test-browser
before_script:
  - cd example; ./start.sh & cd ..
  - sleep 3